apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-clusterrole-comprehensive
rules:
  - apiGroups: ["*"] # All API groups
    resources: ["*"] # All resources
    verbs: ["*"] # All actions (get, list, watch, create, update, delete, etc.)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-clusterrolebinding-comprehensive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-clusterrole-comprehensive # Matches the ClusterRole name above.
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller # The service account used by Argo CD.
    namespace: automation # The namespace where Argo CD is installed.
