apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    repeatInterval: 30m
    receiver: "null"
    routes:
      - matchers:
          - name: alertname
            value: HighCpuUsage
        receiver: "send-email"
      - matchers:
          - name: alertname
            value: PodRestart
        receiver: "send-email"
        repeatInterval: 5m
  receivers:
    - name: "send-email"
      emailConfigs:
        - to: rollsroyce221007@gmail.com
          from: rollsroyce221007@gmail.com
          sendResolved: false
          smarthost: smtp.gmail.com:587
          requireTLS: true
          authUsername: rollsroyce221007@gmail.com
          authIdentity: rollsroyce221007@gmail.com
          authPassword:
            name: mail-pass
            key: gmail-pass
    - name: "null"
