name: Trigger Jenkins Job on App Changes

on:
  push:
    paths:
      - 'application/**'  # Trigger when any file inside "application" changes

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -u "admin:11354643ca88a20b99549846c2f52d5c94" -X POST "http://20.5.171.46:8080/job/observability/buildWithParameters?token=test"
